kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: USER
  name: USER
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  name: USER
  namespace: kube-system
secrets:
- name: USER-token
